### ISSUE TITLE
Calculate Axis Forces

### ISSUE THREAD

**Issue by CarlesNV11** [Integrated-Project-2-2024-UVic-UCC/anti-puzzle#29]

**Comment by RRoura** [comment]
i can't find the intrinsic resistance of our sliding block and i will use this instead, because it has to be more or less the same.


![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/3a290127-dcbe-4d5b-84bd-a39dd30f1d52)

**Comment by RRoura** [comment]
sliding block propulsion force


![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/c10d3733-46dd-4c90-9f6f-a9cc1eb6c416)

**Comment by RRoura** [comment]
And the propulsion force of the Y axis is the same of the sliding block but changing the W, we have to sum the W of the other pieces that moves in the Y axis.


![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/76d36f01-9a5e-472a-bb31-9cd073fc41ee)
