### ISSUE TITLE
Design Piece

### ISSUE THREAD

**Issue by CarlesNV11** [Integrated-Project-2-2024-UVic-UCC/anti-puzzle#33]

**Comment by RRoura** [comment]
The piece design has been carefully considered with regard to the magnet we'll use, as well as the player's comfort when gripping and playing with it.

![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/3ac0a243-4f72-4416-ae23-748cd4f4f568)




![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/bef7b842-e978-470a-a5c2-16ebc267272d)



![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/2f90d8d7-9787-40b4-a0cc-b2427163ca36)
