### ISSUE TITLE
Redisign First Structure Prototype

### ISSUE THREAD

**Issue by CarlesNV11** [Integrated-Project-2-2024-UVic-UCC/anti-puzzle#34]

**Comment by RRoura** [comment]
we have redisigned the structure of the game based on the previous design and definition of our core XY movement.



![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/2a113864-c6c7-4fc6-80dc-627d646308d1)




![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/d2c29134-845b-4846-9a00-82a009393ea6)
