### ISSUE TITLE
Redisign Structure

### ISSUE THREAD

**Issue by CarlesNV11** [Integrated-Project-2-2024-UVic-UCC/anti-puzzle#39]

**Comment by RRoura** [comment]
![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/fe51e333-ac30-4cc8-8a95-865bf2c6495e)



![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/be685404-a05b-4d6a-9540-6dfaf3d59fcb)

The structural layout has undergone a redesign aimed at optimizing the overall user experience. One significant modification involves raising the base of the piece, a strategic adjustment intended to eliminate any potential hindrances that might impede the fluid movement of both the game elements and the user interacting with the system. 

![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/98a7936b-315b-4454-be4f-e145b555cbbd)



![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/9d3642b2-6811-4274-96de-2e95d88c8112)



![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/7056ba03-65b7-493e-8db3-3610fdd90bd4)

Additionally, in accordance with the provided instructions, we have successfully integrated a dedicated system designed to facilitate the tensioning of the belts, ensuring optimal performance and reliability of the mechanism.

**Comment by RRoura** [comment]
![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/bb97d572-82f2-4c8f-a269-613c9b85d054)



![Image](https://github.com/Integrated-Project-2-2024-UVic-UCC/anti-puzzle/assets/158278908/2493df57-a54f-49e9-9bb2-5bd60c61f1b3)

This would be the final prototype.
